### ISSUE TITLE
archiver - extra settings

### ISSUE THREAD

**Issue by osnet** [mlan/docker-kopano#13]
In addition to get the archiver work you might take some more action as considered.

- You need to add the archiver in your AD / LDAP environment 
  Just manually add a new member computer like this:
![image](https://user-images.githubusercontent.com/1938728/102692408-47b83b00-4213-11eb-811e-1cf87a0be7c8.png)

- Enable archiver possibility to yout user(s)
![image](https://user-images.githubusercontent.com/1938728/102692443-80581480-4213-11eb-9e43-cf2a693a413c.png)
![image](https://user-images.githubusercontent.com/1938728/102692449-8d750380-4213-11eb-876c-fafbca511d55.png)
Search/Choose archive server added  before
![image](https://user-images.githubusercontent.com/1938728/102692463-ab426880-4213-11eb-944a-38faa634f372.png)

- modify /etc/kopano/archiver.cfg to your needs

```
[coming from .env]
mysql_database = kopano
mysql_host = db-arc
mysql_password = secret
mysql_user = kopano
[/coming from .env]

### Following has to be set in order to make it work ###
server_socket = file:///var/run/kopano/server.sock
####

## edit this like you wish to ###

archive_enable = yes
archive_after = 2

stub_enable = yes
stub_after = 60
stub_unread = no

delete_enable = yes
delete_after = 365
stub_unread = yes

purge_enable = yes
purge_after = 3650

cleanup_action = store
cleanup_follow_purge_after = yes

enable_auto_attach = yes
auto_attach_writable = no

```

not to mention the modifications  in  .env or docker-compose.yml

################

@mlan  any way to configure this in .env ? 

Again many many thanks for this brilliant work !!!

**Comment by mlan** [comment]
Hi @osnet 

Many thanks for sharing this valuable information. Looking at you remarks on AD/LDAP I get the feeling one needs to enable the archiver for each user individually. Is that so?

Configuration using `.env` should already work. The `docker-comose.yml` snippet below should do it, but i have not tested it.

```yaml
services:
  app:
    image: mlan/kopano
    networks:
      - backend
    ports:
      - "127.0.0.1:8008:80"    # WebApp & EAS (alt. HTTP)
      - "127.0.0.1:143:143"    # IMAP (not needed if all devices can use EAS)
      - "127.0.0.1:110:110"    # POP3 (not needed if all devices can use EAS)
      - "127.0.0.1:8080:8080"  # ICAL (not needed if all devices can use EAS)
      - "127.0.0.1:993:993"    # IMAPS (not needed if all devices can use EAS)
      - "127.0.0.1:995:995"    # POP3S (not needed if all devices can use EAS)
      - "127.0.0.1:8443:8443"  # ICALS (not needed if all devices can use EAS)
    depends_on:
      - auth
      - db
      - mta
    environment:
      - USER_PLUGIN=ldap
      - LDAP_URI=ldap://auth:389/
      - SERVER_MYSQL_HOST=db-srv
      - ARCHIVER_MYSQL_HOST=db-arc
      - MYSQL_DATABASE=kopano
      - MYSQL_PASSWORD=secret
      - MYSQL_USER=kopano
      - SERVER_SOCKET=file:///var/run/kopano/server.sock
      - LDAP_SEARCH_BASE=${LDAP_BASE-dc=example,dc=com}
      - LDAP_USER_TYPE_ATTRIBUTE_VALUE=${LDAP_USEROBJ-posixAccount}
      - LDAP_GROUP_TYPE_ATTRIBUTE_VALUE=${LDAP_GROUPOBJ-posixGroup}
      - LDAP_GROUPMEMBERS_ATTRIBUTE_TYPE=dn
      - LDAP_PROPMAP=
      - IMAP_LISTEN=*:143                       # also listen to eth0
      - POP3_LISTEN=*:110                       # also listen to eth0
      - ICAL_LISTEN=*:8080                      # also listen to eth0
      - IMAPS_LISTEN=*:993                      # enable TLS
      - POP3S_LISTEN=*:995                      # enable TLS
      - ICALS_LISTEN=*:8443                     # enable TLS
      - ARCHIVE_ENABLE=yes
      - ARCHIVE_AFTER=2
      - STUB_ENABLE=yes
      - STUB_AFTER=60
      - STUB_UNREAD=no
      - DELETE_ENABLE=yes
      - DELETE_AFTER=365
      - STUB_UNREAD=yes
      - PURGE_ENABLE=yes
      - PURGE_AFTER=3650
      - CLEANUP_ACTION=store
      - CLEANUP_FOLLOW_PURGE_AFTER=yes
      - ENABLE_AUTO_ATTACH=yes
      - AUTO_ATTACH_WRITABLE=no
      - CRONTAB_ENTRY1=0 1 * * * root kopano-archiver -A
      - CRONTAB_ENTRY2=0 3 * * 0 root kopano-archiver -C
    volumes:
      - app-conf:/etc/kopano
      - app-atch:/var/lib/kopano/attachments
      - app-sync:/var/lib/z-push
      - app-spam:/var/lib/kopano/spamd          # kopano-spamd integration
      - /etc/localtime:/etc/localtime:ro        # Use host timezone
```
