### ISSUE TITLE
persistent external volumes

### ISSUE THREAD

**Issue by osnet** [mlan/docker-kopano#2]
Hi there,
you made a great piece of kopano-docker! Much better than the main unoffical repo!! 

I managed successfully to connect to my samba domain ripped out some openldap stuff and  it works like a charm.

BUT ... : ))
Since i have a different docker setup, i dont want to have stuff located in /var/lib/docker/volumes, i am trying to map 
all the app-* mta und db stuff directly under my project directory.
i.e.  /var/docker/PROJECTNAME/DATADIR

```    volumes:
      - ./app-conf:/etc/kopano:rw
      - ./app-atch:/var/lib/kopano/attachments:rw
      - ./app-sync:/var/lib/z-push:rw
      - ./app-spam:/var/lib/kopano/spamd:rw     # kopano-spamd integration
      - /etc/localtime:/etc/localtime:ro    # Use host timezone
      - ./ldap.cfg:/etc/kopano/ldap.cfg
```
sadly your image does not fully populate its files to these directorys 
any chance to fix this ?

thanks in advance

**Comment by osnet** [comment]
mmh  solved ... 

```
volumes:
  app-atch:
   driver: local
   driver_opts:
     type: none
     device: $PWD/app-atch
     o: bind
  app-conf:
   driver: local
   driver_opts:
     type: none
     device: $PWD/app-conf
     o: bind
  app-spam:
   driver: local
   driver_opts:
     type: none
     device: $PWD/app-spam
     o: bind
  app-sync:
   driver: local
   driver_opts:
     type: none
     device: $PWD/app-sync
     o: bind
  db:
   driver: local
   driver_opts:
     type: none
     device: $PWD/db
     o: bind
  mta:
   driver: local
   driver_opts:
     type: none
     device: $PWD/mta
     o: bind
```

dirty af, but works, besides clamav : )

**Comment by mlan** [comment]
Hello @osnet,

I love to learn that you find this repo useful. :)

Great that you found a solution. If you figure out a better way to solve this, you are very welcome to 
share it here.

/mlan

**Comment by mlan** [comment]
BTW

I only use the demo/docker-compose.yml for testing. In my live system I use zfs like this:
```yml
volumes:
  mail-mta:
    name: rpool/docker-volumes/${COMPOSE_PROJECT_NAME}_mail-mta
    driver: zfs
...
```

**Comment by osnet** [comment]
nya ... my docker are XCP-NG/Xen vms with nfs storage ... 
lvm within nfs on xfs on lvm  blaaaaaa -.- 

but i figured out  that my solution  fixes  just  90% ...  there  are some symlinks in the project. 
but thats  kopano related.  so i had to switch a lil bit ... 


step 1:   add local-persist  driver to docker 
```  
curl -fsSL https://raw.githubusercontent.com/MatchbookLab/local-persist/master/scripts/install.sh | sudo bash

```
source : 
https://github.com/wodby/docker4drupal/issues/260
https://github.com/MatchbookLab/local-persist

step 2:

modified compose yaml
```
volumes:
  app-atch:
   driver: local-persist
   driver_opts:
     mountpoint: /var/docker/kopano/app-atch
  app-conf:
   driver: local-persist
   driver_opts:
     mountpoint: /var/docker/kopano/app-conf
  app-spam:
   driver: local-persist
   driver_opts:
     mountpoint: /var/docker/kopano/app-spam
  app-sync:
   driver: local-persist
   driver_opts:
     mountpoint: /var/docker/kopano/app-sync
  db:
   driver: local-persist
   driver_opts:
     mountpoint: /var/docker/kopano/db
  mta:
   driver: local-persist
   driver_opts:
     mountpoint: /var/docker/kopano/mta

```
: )
